### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jawnnypoo**
Hey, so I recently followed the steps, and this was a missing step in the process. It suggested this solution in the console when I went to deploy, but I figure this might be a good step to include in the README

### CODE REVIEW

**Comment by mg-1999** [comment]
I also needed to do this before i was able to push.
So it should really be added to the README.

**Comment by Jawnnypoo** [comment]
Any thoughts on this @renaudcerrato ?

**Comment by renaudcerrato** [comment]
I'm not a Maven user, but I can hardly believe that such a widespread tool requires the user to both  mess with HTTP headers and force him to know the internals of basic authentication in order to generate the base64 encoded token.

**Comment by Jawnnypoo** [comment]
Hrm? I think you may be responding to the wrong PR here @renaudcerrato This is just about adding an additional instruction to the README

**Comment by renaudcerrato** [comment]
You're right, sorry. I created a dozen of appengine projects, but I never had to deal with your issue. Can you try to create a dummy project while redacting the exact steps you took?

**Pull request closed without merging**
