### PR TITLE
adding a simple delete artifact functionality and forcing https always

### PR DESCRIPTION
**Pull request by mohamnag**

### CODE REVIEW

**Comment by renaudcerrato** [comment]
Thanks @mohamnag, but while I'm agree with the "force https", I can't agree on the delete artifact method:

1- The method should be @DELETE, not a @GET
2- Artifacts shouldn't be deleted IMO, or at least not from your web browser.
3- If that's **really** needed, you can do that from your Google Cloud Storage instead.

**Comment by renaudcerrato** [comment]
Feel free to send a new PR for the [`force https`](http://stackoverflow.com/questions/5367974/https-only-in-google-app-engine).

**Comment by mohamnag** [comment]
I was actually on the process of fixing the delete method and just pushed.

**Comment by renaudcerrato** [comment]
Yes, just seen that, but being able to delete artifacts from your web-browser sounds a bit over-powered to me. Moreover, artifacts should not be deleted IMO. Feel free to post a separate PR about it, and I'll wait for more feedbacks before merging it?

**Comment by mohamnag** [comment]
it depends on how you look at the fact, this is not a full featured enterprise level repo manager. What happened to me was that I pushed wrong artifacts and there was no way of deleting them except for accessing GC API. 

I have to take a bit more time and maybe reconsider it.

**Comment by renaudcerrato** [comment]
Sure, I understand. But accessing GCS to delete an artifact sounds to me like a nice security layer above admin ;)

**Comment by renaudcerrato** [comment]
Feel free to split your next PR for easier tracking & maintenance.

**Comment by mohamnag** [comment]
honestly I dont see any additional security advantage as this implementation anyway allows overwriting the artifacts. 

The part for forcing https is the change in web.xml file in case you want to apply it.

**Comment by renaudcerrato** [comment]
FYI, I forced https and moved to mustache for templating.

Le ven. 11 nov. 2016 02:41, Mohammad Naghavi <notifications@github.com> a
écrit :

**Pull request closed without merging**
